# Generated by Django 4.2.2 on 2023-06-13 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
