# Generated by Django 4.2.2 on 2023-06-11 17:18

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_urls', models.CharField(max_length=2083)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=builtins.id, max_length=255),
            preserve_default=False,
        ),
    ]
